name: LOC Graph

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  loc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate LOC Graph
        uses: botforge-pro/loc-graph-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: loc-data
          output_dir: .loc
          title: "Lines of Code"